apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization 
metadata:
  name: kustomization
spec:
  interval: 30s
  timeout: 2m
  wait: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: repo-helm-release
  path: /dev
  prune: true